variables: 
  templateFile: '$(Build.Repository.LocalPath)/Bicep/main.bicep'
  templateFileDir: '$(Build.Repository.LocalPath)/Bicep'
  parametersFile: '$(Build.Repository.LocalPath)/Bicep/env/dev.bicepparam'
  DeploymentName: 'agentpool'
  iacReportScriptFolder: '$(Build.Repository.LocalPath)/Scripts'

name: '$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:r)'

pool: 'linux-agent-pool'
  # vmImage: 'ubuntu-latest'

stages:
- stage: checkov_scan
  displayName: checkov scan
  jobs:
  - job: checkov_scan
    displayName: checkov scan
    steps:
    # Checkov Ignore Checks
    - task: Bash@3
      name: Checkov_Ignore_Checks
      inputs:
        targetType: 'inline'
        script: |
          python3 checkov_ignore.py
        workingDirectory: '$(iacReportScriptFolder)'
      displayName: "Checkov Ignore Checks"

    # Run Checkov Scan
    - task: Bash@3
      name: Run_Checkov_Scan
      inputs:
        targetType: 'inline'
        script: |
          echo "[INFO], Running Checkov scan..."
          checkov --directory $(templateFileDir) --file ${{ variables.templateFile }} --framework bicep --soft-fail --quiet --compact --output junitxml \ -
          --skip-check $(SKIP_CHECKS) > $(System.DefaultWorkingDirectory)/bicep-checkov-report.xml 
      displayName: "Run Checkov for Compliance check"

    - task: PublishTestResults@2
      inputs:
        testRunTitle: "Checkov Results"
        failTaskOnFailedTests: true
        testResultsFormat: "JUnit"
        testResultsFiles: "bicep-checkov-report.xml"
        searchFolder: "$(System.DefaultWorkingDirectory)"
      displayName: "Publish Test results"