variables: 
  templateFile: '$(Build.Repository.LocalPath)/Bicep/main.bicep'
  parametersFile: '$(Build.Repository.LocalPath)/Bicep/env/dev.bicepparam'
  DeploymentName: 'agentpool'
  iacReportScriptFolder: '$(Build.Repository.LocalPath)/Scripts'

name: '$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:r)'

pool: 'linux-agent-pool'
  # vmImage: 'ubuntu-latest'

stages:
- stage: checkov_scan
  displayName: checkov scan
  jobs:
  - job: checkov_scan
    displayName: checkov scan
    steps:
    # Checkov Ignore Checks
    - task: Bash@3
      name: Checkov_Ignore_Checks
      inputs:
        targetType: 'inline'
        script: |
          python checkov_ignore.py
        workingDirectory: '$(iacReportScriptFolder)'
      displayName: "Checkov Ignore Checks"

    # Run Checkov Scan
    - task: Bash@3
      name: Run_Checkov_Scan
      inputs:
        targetType: 'inline'
        script: |
          echo "[INFO], Running Checkov scan..."
          mkdir -p $(System.DefaultWorkingDirectory)/results/         
          checkov --file ${{ variables.templateFile }} --framework bicep --soft-fail --quiet --compact --output sarif --output-file-path $(System.DefaultWorkingDirectory)/results/ --skip-check $(SKIP_CHECKS)
      displayName: "Run Checkov for Compliance check"

    # Publish SARIF Logs
    - task: PublishBuildArtifacts@1
      name: Publish_Test_SARIF_logs
      displayName: "Publish Test SARIF logs"
      inputs:
        pathToPublish: $(System.DefaultWorkingDirectory)/results/
        artifactName: CodeAnalysisLogs