pool:
  name: linux-agent-pool

name: Azure Bicep IaC Compliance

variables:
  serviceConnectionName: 'eng-lab-automation'
  location: 'uksouth'
  templateFile: '$(Build.Repository.LocalPath)/Bicep/main.bicep'
  parameterFile: '$(Build.Repository.LocalPath)/Bicep/env/dev.bicepparam'
  DeploymentName: main
  subscriptionId: 800eeb5c-ab87-468f-800b-d9ca632b4f73

stages:
  - stage: CodeComplianceCheck
    jobs:
      - job: RunComplianceChecks
        displayName: Run Code Compliance Checks
        steps:
          - task: CmdLine@2
            name: ValidateParametersFile
            displayName: Validate Parameters File
            inputs:
              script: |
                az bicep build-params --file $(parameterFile) --stdout

          - task: Bash@3
            name: CheckBicepFormat
            displayName: "Check Bicep Template Format"
            inputs:
              targetType: 'inline'
              script: |
                formatted_output=$(mktemp)
                az bicep format --file $(templateFile) --outfile $formatted_output
                if ! diff -q $(templateFile) $formatted_output; then
                  echo "Bicep file format validation failed. Please run 'az bicep format --file main.bicep' locally to fix."
                  exit 1
                else
                  echo "Bicep file is correctly formatted."
                fi

          - task: Bash@3
            name: RunBicepLint
            displayName: Run Bicep Linter
            inputs:
              targetType: 'inline'
              script: |
                mkdir -p $(System.DefaultWorkingDirectory)/test
                bicep lint $(templateFile) --diagnostics-format sarif > $(System.DefaultWorkingDirectory)/test/bicep-linter.sarif

          - task: Bash@3
            name: RunCheckovComplianceScan
            displayName: Run Checkov Compliance Scan
            inputs:
              targetType: 'inline'
              script: |
                checkov --file $(templateFile) --framework bicep \
                --soft-fail --quiet --compact --output sarif \
                --output-file-path $(System.DefaultWorkingDirectory)/test > bicep-checkov.sarif

          - task: PublishBuildArtifacts@1
            name: PublishCodeAnalysisReports
            displayName: Publish Code Analysis Reports
            condition: always()
            inputs:
              pathToPublish: $(System.DefaultWorkingDirectory)/test/
              artifactName:  CodeAnalysisLogs # required to show up in the scans tab
              
  - stage: Deploy
    dependsOn: CodeComplianceCheck
    condition: succeeded()
    jobs:
      - deployment: Deploy
        environment: DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureCLI@2
                  name: DeployInfrastructureResources
                  displayName: Deploy Infrastructure Resources
                  inputs:
                    azureSubscription: $(serviceConnectionName)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az deployment sub create --location uksouth \
                      --template-file $(templateFile) \
                      --parameters $(parameterFile)
                    workingDirectory: $(Pipeline.Workspace)
