pr: none
trigger:
  batch: false
  branches:
    include:
    - main
  paths:
    include:
    - AzureDevOps/Bicep/*

variables:
  major: 1
  minor: 0
  patch: $[counter(format('{0}.{1}-{2}', variables['major'], variables['minor'], variables['Build.SourceBranchName']), 1)]
  ${{ if eq( variables['Build.SourceBranchName'], 'main' ) }}: 
    branch: ''
  ${{ if ne( variables['Build.SourceBranchName'], 'main' ) }}: 
    branch: -${{ variables['Build.SourceBranchName'] }}

name: $(major).$(minor).$(patch)$(branch)-Infrastructure

pool:
  vmImage: ubuntu-latest

stages:
### Validate
- template: ../Templates/Stages/bicep-validation-stage.yml
  parameters:
    name: Validate
    displayName: Validate
    dependsOn: []
    variables:
    - template: ../Variables/variables-dev.yml
    - template: ../Variables/variables-global.yml

### Lint
- template: ../Templates/Stages/bicep-lint-stage.yml
  parameters:
    name: Lint
    displayName: Lint
    dependsOn: Validate
    variables:
    - template: ../Variables/variables-dev.yml
    - template: ../Variables/variables-global.yml

### Manual Deployment approval
- template: ../Templates/Stages/manual-approval-stage.yml
  parameters:
    name: ManualApproval
    displayName: ManualApproval
    dependsOn: Lint
    variables:
    - template: ../Variables/variables-dev.yml
    - template: ../Variables/variables-global.yml

### Deploy Infrastructure BVT
- template: ../Templates/Stages/bicep-deployment-stage.yml
  parameters:
    name: Deploy_Infrastructure_BVT
    displayName: Deploy Infrastructure BVT
    dependsOn: ManualApproval
    variables:
    - template: ../Variables/variables-dev.yml
    - template: ../Variables/variables-global.yml
    environment: BVT
