pr: none
trigger:
  batch: false
  branches:
    include:
    - main
  paths:
    include:
    - AzureDevOps/Bicep/*

variables:
  major: 1
  minor: 0
  patch: $[counter(format('{0}.{1}-{2}', variables['major'], variables['minor'], variables['Build.SourceBranchName']), 1)]
  ${{ if eq( variables['Build.SourceBranchName'], 'main' ) }}: 
    branch: ''
  ${{ if ne( variables['Build.SourceBranchName'], 'main' ) }}: 
    branch: -${{ variables['Build.SourceBranchName'] }}

name: $(major).$(minor).$(patch)$(branch)-Infrastructure

pool:
  name: linux-agentpool

stages:
### Validate
- template: ../Templates/Stages/bicep-validation-stage.yml
  parameters:
    name: Validate
    displayName: Validate
    variables:
    - template: ../Variables/variables-dev.yml

### Preview Deployment
- template: ../Templates/Stages/bicep-preview-stage.yml
  parameters:
    name: Preview_Deployment
    displayName: Preview Deployment
    dependsOn: Validate
    variables:
    - template: ../Variables/variables-dev.yml

### Deploy Infrastructure
- template: ../Templates/Stages/bicep-deployment-stage.yml
  parameters:
    name: Infrastructure_Deployment
    displayName: Infrastructure Deployment
    dependsOn: Preview_Deployment
    variables:
    - template: ../Variables/variables-dev.yml
    environment: DEV
